---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: infisical

# helmCharts:
#   - name: redis
#     repo: oci://${ARGOCD_ENV_CONTAINER_REGISTRY_DOMAIN}/raulstechtips/redis
#     version: 22.0.5
#     releaseName: redis-infisical
#     namespace: infisical
#     valuesFile: values/prod.yaml

resources:
  - manifests/secrets/secret-redis-infisical-credential.yaml
