---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: infisical

helmCharts:
  - name: redis
    repo: https://charts.bitnami.com/bitnami
    version: 20.11.5
    releaseName: redis-infisical
    namespace: infisical
    valuesFile: values/prod.yaml

resources:
  - manifests/storage/longhorn-redis-infisical.yaml
  - manifests/secrets/secret-redis-infisical-credential.yaml
