---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: infisical-secret-authentik-redis-credentials-secret
  namespace: authentik
spec:
  resyncInterval: 60
  hostAPI: "${INFISICAL_HOST_API}"
  authentication:
    universalAuth:
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: infisical
      secretsScope:
        projectSlug: "${INFISICAL_PROJECT_SLUG}"
        envSlug: "${INFISICAL_ENV_SLUG}"
        secretsPath: "/authentik/redis"
        recursive: true
  managedKubeSecretReferences:
    - secretName: authentik-redis-admin-credentials-secret
      secretNamespace: authentik
      secretType: Opaque
      creationPolicy: Owner
      template:
        includeAllSecrets: false
        data:
          redis-password: "{{ .password.Value }}"
