---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: infisical-secret-arc-github-app
  namespace: arc-runners
spec:
  hostAPI: "${ARGOCD_ENV_INFISICAL_PROD_HOST_API}"
  authentication:
    universalAuth:
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: infisical
      secretsScope:
        projectSlug: "${ARGOCD_ENV_INFISICAL_PROJECT_SLUG}"
        envSlug: "${ARGOCD_ENV_INFISICAL_ENV_SLUG}"
        secretsPath: "/github/arc"
        recursive: true
  managedKubeSecretReferences:
    - secretName: arc-github-app
      secretNamespace: arc-runners
      secretType: Opaque
      creationPolicy: Owner
      template:
        includeAllSecrets: false
        data:
          github_app_id: "{{ .APP_ID.Value }}"
          github_app_installation_id: "{{ .INSTALLATION_ID.Value }}"
          github_app_private_key: "{{ .PRIVATE_KEY.Value }}"
