---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: stage-raulstechtips
  namespace: default
spec:
  secretName: stage-raulstechtips-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "*.stage.${ARGOCD_ENV_DOMAIN}"
  dnsNames:
    - "stage.${ARGOCD_ENV_DOMAIN}"
    - "*.stage.${ARGOCD_ENV_DOMAIN}"
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
