---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default

helmCharts:
  - name: secrets-operator
    repo: https://dl.cloudsmith.io/public/infisical/helm-charts/helm/charts/
    version: v0.9.1
    releaseName: infisical-secrets-operator
    namespace: default
    valuesFile: values/prod.yaml
