---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pg-infisical-internal-certificate
  namespace: infisical
  labels:
    cnpg.io/reload: ""
spec:
  secretName: pg-infisical-internal-tls
  duration: 8760h # 1 year
  renewBefore: 720h # 30 days
  subject:
    organizations:
      - raulstechtips
  dnsNames:
    - pg-infisical-rw
    - pg-infisical-rw.infisical
    - pg-infisical-rw.infisical.svc
    - pg-infisical-rw.infisical.svc.cluster.local
    - pg-infisical-ro
    - pg-infisical-ro.infisical
    - pg-infisical-ro.infisical.svc
    - pg-infisical-ro.infisical.svc.cluster.local
    - pg-infisical-r
    - pg-infisical-r.infisical
    - pg-infisical-r.infisical.svc
    - pg-infisical-r.infisical.svc.cluster.local
  issuerRef:
    name: raulstechtips-internal-ca-issuer
    kind: ClusterIssuer
