---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: harbor

resources:
  - manifests/cluster.yaml
  - manifests/secrets/pg-harbor-admin-credentials.yaml
  - manifests/scheduled-backup.yaml
