---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: infisical-secret-github-registry-secret
  namespace: default
  labels:
    cnpg.io/reload: "true"
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
spec:
  hostAPI: "${ARGOCD_ENV_INFISICAL_PROD_HOST_API}"
  authentication:
    universalAuth:
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: infisical
      secretsScope:
        projectSlug: "${ARGOCD_ENV_INFISICAL_PROJECT_SLUG}"
        envSlug: prod
        secretsPath: "/registry"
        recursive: true
  managedKubeSecretReferences:
    - secretName: github-registry-secret
      secretNamespace: default
      secretType: kubernetes.io/dockerconfigjson
      creationPolicy: Owner
      template:
        includeAllSecrets: false
        data:
          # ONLY STAGING SECRETS
          .dockerconfigjson: "{{ .DOCKER_CONFIG_JSON.Value }}"
