---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: raulstechtips-internal-ca
  namespace: cert-manager
spec:
  isCA: true
  commonName: "k8s-internal-ca.cluster.local"
  secretName: raulstechtips-internal-ca-key-pair
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
