---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
spec:
  template:
    spec:
      containers:
        - name: argocd-repo-server
          envFrom:
            - secretRef:
                name: argocd-app-env
          env:
            - name: ARGOCD_CMP_SERVER
              value: "1"
