---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev

resources:
  - manifests/cluster.yaml
  - manifests/secrets/pg-dev-admin-credentials.yaml
  - manifests/secrets/pg-huginn-database-credential-secret.yaml
  - manifests/databases/pg-huginn.yaml
