---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default

helmCharts:
  - name: reflector
    repo: https://emberstack.github.io/helm-charts
    version: 9.0.322
    releaseName: reflector
    namespace: default
    valuesFile: values/prod.yaml
