---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: infisical-secret-longhorn-minio-secret
  namespace: longhorn-system
spec:
  hostAPI: ${ARGOCD_ENV_INFISICAL_PROD_HOST_API}
  authentication:
    universalAuth:
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: infisical
      secretsScope:
        projectSlug: ${ARGOCD_ENV_INFISICAL_PROJECT_SLUG}
        envSlug: ${ARGOCD_ENV_INFISICAL_ENV_SLUG}
        secretsPath: "/minio/users/longhorn"
        recursive: true
  managedKubeSecretReferences:
    - secretName: minio-secret
      secretNamespace: longhorn-system
      secretType: Opaque
      creationPolicy: Owner
      template:
        includeAllSecrets: false
        data:
          AWS_ACCESS_KEY_ID: "{{ .CONSOLE_ACCESS_KEY.Value }}"
          AWS_SECRET_ACCESS_KEY: "{{ .CONSOLE_SECRET_KEY.Value }}"
          AWS_ENDPOINTS: "https://${ARGOCD_ENV_S3_PROD_API_DOMAIN}"
