---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: harbor

helmCharts:
  - name: redis
    repo: oci://ghcr.io/raulstechtips
    version: 22.0.5
    releaseName: redis-harbor
    namespace: harbor
    valuesFile: values/prod.yaml

resources:
  - manifests/secrets/redis-secret.yaml
