---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: infisical-secret-tenant-s3-openid-secrets
  namespace: minio
spec:
  hostAPI: "${ARGOCD_ENV_INFISICAL_PROD_HOST_API}"
  authentication:
    universalAuth:
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: infisical
      secretsScope:
        projectSlug: "${ARGOCD_ENV_INFISICAL_PROJECT_SLUG}"
        envSlug: "${ARGOCD_ENV_INFISICAL_ENV_SLUG}"
        secretsPath: "/minio/oidc"
        recursive: true
  managedKubeSecretReferences:
    - secretName: tenant-s3-openid-secrets
      secretNamespace: minio
      secretType: Opaque
      creationPolicy: Owner
      template:
        includeAllSecrets: false
        data:
          MINIO_IDENTITY_OPENID_CONFIG_URL: "{{ .MINIO_IDENTITY_OPENID_CONFIG_URL.Value }}"
          MINIO_IDENTITY_OPENID_CLIENT_ID: "{{ .MINIO_IDENTITY_OPENID_CLIENT_ID.Value }}"
          MINIO_IDENTITY_OPENID_CLIENT_SECRET: "{{ .MINIO_IDENTITY_OPENID_CLIENT_SECRET.Value }}"
          MINIO_IDENTITY_OPENID_SCOPES: "{{ .MINIO_IDENTITY_OPENID_SCOPES.Value }}"
          MINIO_IDENTITY_OPENID_REDIRECT_URI: "{{ .MINIO_IDENTITY_OPENID_REDIRECT_URI.Value }}"
