---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: infisical-secret-tenant-s3-minio-env-configuration
  namespace: minio
spec:
  hostAPI: "${ARGOCD_ENV_INFISICAL_PROD_HOST_API}"
  authentication:
    universalAuth:
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: infisical
      secretsScope:
        projectSlug: "${ARGOCD_ENV_INFISICAL_PROJECT_SLUG}"
        envSlug: "${ARGOCD_ENV_INFISICAL_ENV_SLUG}"
        secretsPath: "/minio"
        recursive: true
  managedKubeSecretReferences:
    - secretName: tenant-s3-minio-env-configuration
      secretNamespace: minio
      secretType: Opaque
      creationPolicy: Owner
      template:
        includeAllSecrets: false
        data:
          config.env: |
            export MINIO_ROOT_USER={{ .MINIO_ROOT_USER.Value }}
            export MINIO_ROOT_PASSWORD={{ .MINIO_ROOT_PASSWORD.Value }}
