---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: infisical-secret-tenant-authentik-minio-users
  namespace: authentik
spec:
  hostAPI: "${ARGOCD_ENV_INFISICAL_PROD_HOST_API}"
  authentication:
    universalAuth:
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: infisical
      secretsScope:
        projectSlug: "${ARGOCD_ENV_INFISICAL_PROJECT_SLUG}"
        envSlug: "${ARGOCD_ENV_INFISICAL_ENV_SLUG}"
        secretsPath: "/authentik/minio"
        recursive: true
  managedKubeSecretReferences:
    - secretName: tenant-authentik-minio-users
      secretNamespace: authentik
      secretType: Opaque
      creationPolicy: Owner
      template:
        includeAllSecrets: false
        data:
          CONSOLE_ACCESS_KEY: "{{ .CONSOLE_ACCESS_KEY.Value }}"
          CONSOLE_SECRET_KEY: "{{ .CONSOLE_SECRET_KEY.Value }}"
          CONSOLE_PBKDF_SALT: "{{ .CONSOLE_PBKDF_SALT.Value }}"
          CONSOLE_PBKDF_PASSPHRASE: "{{ .CONSOLE_PBKDF_PASSPHRASE.Value }}"
