---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: infisical-secret-tenant-authentik-minio-env-configuration
  namespace: authentik
spec:
  hostAPI: "${INFISICAL_PROD_HOST_API}"
  authentication:
    universalAuth:
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: infisical
      secretsScope:
        projectSlug: "${INFISICAL_PROJECT_SLUG}"
        envSlug: "${INFISICAL_ENV_SLUG}"
        secretsPath: "/authentik/env"
        recursive: true
  managedKubeSecretReferences:
    - secretName: tenant-authentik-minio-env-configuration
      secretNamespace: authentik
      secretType: Opaque
      creationPolicy: Owner
      template:
        includeAllSecrets: false
        data:
          config.env: |
            export MINIO_ROOT_USER={{ .AUTHENTIK_STORAGE__MEDIA__S3__ACCESS_KEY.Value }}
            export MINIO_ROOT_PASSWORD={{ .AUTHENTIK_STORAGE__MEDIA__S3__SECRET_KEY.Value }}
