---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-ingress
  namespace: argocd
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`${ARGOCD_ENV_ARGON_PROD_DOMAIN}`)
      kind: Rule
      priority: 10
      middlewares:
        - name: default-headers
          namespace: default
      services:
        - name: argocd-server
          port: 80
    - match: Host(`${ARGOCD_ENV_ARGON_PROD_DOMAIN}`) && Header(`Content-Type`, `application/grpc`)
      kind: Rule
      priority: 11
      middlewares:
        - name: default-headers
          namespace: default
      services:
        - name: argocd-server
          port: 80
  tls:
    secretName: prod-raulstechtips-tls
