---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: oauth2-proxy

helmCharts:
  - name: oauth2-proxy
    repo: https://oauth2-proxy.github.io/manifests
    version: 8.5.0
    releaseName: oauth2-proxy
    namespace: oauth2-proxy
    valuesFile: values/prod.yaml

resources:
  - manifests/ingress/prod.yaml
  - manifests/secrets/config-secret.yaml
  - manifests/secrets/client-secret.yaml
