---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: authentik

helmCharts:
  - name: authentik
    repo: https://charts.goauthentik.io
    version: 2025.4.0
    releaseName: authentik
    namespace: authentik
    valuesFile: values/prod.yaml

resources:
  - manifests/ingress/prod.yaml
  - manifests/ingress/middleware/authentik-forward-auth-proxy.yaml
  - manifests/secrets/authentik-env-secret.yaml
