---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: longhorn-system

helmCharts:
  - name: longhorn
    repo: https://charts.longhorn.io
    version: 1.8.1
    releaseName: longhorn
    namespace: longhorn-system
    valuesFile: values/prod.yaml

resources:
  - manifests/ingress/ingress.yaml
  - manifests/storage/longhorn-default-storage-class.yaml
  - manifests/storage/longhorn-storage-class-replicas-1.yaml
  - manifests/storage/longhorn-storage-class-local.yaml
  - manifests/storage/longhorn-volume-snapshot-class.yaml
  - manifests/secrets/secret-longhorn-minio-secret.yaml

patches:
  - path: overlays/patch-longhorn-manager-tlsrsakex-env.yaml
