---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jenkins

helmCharts:
  - name: jenkins
    repo: https://charts.jenkins.io
    version: 5.8.39
    releaseName: jenkins
    namespace: jenkins
    valuesFile: values/prod.yaml

resources:
  - manifests/secrets/secret-jenkins-github-app.yaml
  - manifests/secrets/secret-jenkins-kube-config.yaml
  - manifests/secrets/infisical-secret-jenkins-admin-credentials.yaml
  - manifests/storage/longhorn-jenkins.yaml
  - manifests/ingress/live.yaml
  - manifests/ingress/prod.yaml
  - manifests/ingress/middleware/middleware-github-hooks-ip-allowlist.yaml
