---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: serenemind-app
  namespace: serenemind
  labels:
    app: serenemind-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: serenemind-app
  template:
    metadata:
      labels:
        app: serenemind-app
    spec:
      imagePullSecrets:
        - name: github-registry-secret
      containers:
        - name: serenemind-app
          image: ghcr.io/raulstechtips/serenemind-io:v0.0.5
          ports:
            - containerPort: 8000
              name: http
          envFrom:
            - secretRef:
                name: serenemind-app-secret
            - secretRef:
                name: serenemind-pg-admin-credentials-secret
            - secretRef:
                name: s3-secret
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /health/
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health/
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: webapp
  namespace: serenemind
  labels:
    app: serenemind-app
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: serenemind-app
