---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: infisical-secret-infisical-gateway-environment
  namespace: infisical-gateway
spec:
  hostAPI: "${ARGOCD_ENV_INFISICAL_PROD_HOST_API}"
  authentication:
    universalAuth:
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: infisical
      secretsScope:
        projectSlug: "${ARGOCD_ENV_INFISICAL_PROJECT_SLUG}"
        envSlug: "${ARGOCD_ENV_INFISICAL_ENV_SLUG}"
        secretsPath: "/infisical/gateway"
        recursive: true
  managedKubeSecretReferences:
    - secretName: infisical-gateway-environment
      secretNamespace: infisical-gateway
      secretType: Opaque
      creationPolicy: Owner
      template:
        includeAllSecrets: false
        data:
          username: "{{ .PG_KEYCLOAK_ADMIN_USERNAME.Value }}"
          password: "{{ .PG_KEYCLOAK_ADMIN_PASSWORD.Value }}"
