---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: infisical-secret-airflow-app-secrets
  namespace: airflow
spec:
  hostAPI: ""
  authentication:
    universalAuth:
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: infisical
      secretsScope:
        projectSlug: ""
        envSlug: prod
        secretsPath: "/airflow/app"
        recursive: true
  managedKubeSecretReferences:
    - secretName: airflow-app-secrets
      secretNamespace: airflow
      secretType: Opaque
      creationPolicy: Owner
      template:
        includeAllSecrets: false
        data:
          fernet-key: "{{ .AIRFLOW__CORE__FERNET_KEY.Value }}"
          api-secret-key: "{{ .AIRFLOW__WEBSERVER__SECRET_KEY.Value }}"
          jwt-secret: "{{ .AIRFLOW_JWT_SECRET_KEY.Value }}"
          connection: "redis://:{{ .AIRFLOW_REDIS_PASSWORD.Value }}@redis-airflow-master.airflow.svc.cluster.local:6379/0"
          AIRFLOW_ADMIN_PASSWORD: "{{ .AIRFLOW_ADMIN_PASSWORD.Value }}"
          # redis-password: "{{ .AIRFLOW_REDIS_PASSWORD.Value }}"
