---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: infisical-secret-airflow-database-secrets
  namespace: airflow
spec:
  hostAPI: ""
  authentication:
    universalAuth:
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: infisical
      secretsScope:
        projectSlug: ""
        envSlug: prod
        secretsPath: "/airflow/postgres"
        recursive: true
  managedKubeSecretReferences:
    - secretName: airflow-database-secrets
      secretNamespace: airflow
      secretType: Opaque
      creationPolicy: Owner
      template:
        includeAllSecrets: false
        data:
          connection: "postgresql://{{ .AIRFLOW_POSTGRES_USERNAME.Value }}:{{ .AIRFLOW_POSTGRES_PASSWORD.Value }}@{{ .AIRFLOW_POSTGRES_HOST.Value }}:5432/{{ .AIRFLOW_POSTGRES_DATABASE.Value }}"
          # AIRFLOW_DB_CONNECTION_URL: "postgres://${{ AIRFLOW_POSTGRES_USERNAME.Value }}:${{ .AIRFLOW_POSTGRES_PASSWORD.Value }}@${{ .AIRFLOW_POSTGRES_HOST.Value }}:5432/${{ .AIRFLOW_POSTGRES_DATABASE.Value }}?sslmode=verify-ca&sslrootcert=${{ .AIRFLOW_POSTGRES_SSL_ROOT_CERT.Value }}"
