---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: infisical-secret-airflow-sso-secrets
  namespace: airflow
spec:
  hostAPI: ""
  authentication:
    universalAuth:
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: infisical
      secretsScope:
        projectSlug: ""
        envSlug: prod
        secretsPath: "/airflow/sso"
        recursive: true
  managedKubeSecretReferences:
    - secretName: airflow-sso-secrets
      secretNamespace: airflow
      secretType: Opaque
      creationPolicy: Owner
      template:
        includeAllSecrets: false
        data:
          AIRFLOW__KEYCLOAK_AUTH_MANAGER__CLIENT_ID: "{{ .AIRFLOW__KEYCLOAK_AUTH_MANAGER__CLIENT_ID.Value }}"
          AIRFLOW__KEYCLOAK_AUTH_MANAGER__CLIENT_SECRET: "{{ .AIRFLOW__KEYCLOAK_AUTH_MANAGER__CLIENT_SECRET.Value }}"
          AIRFLOW__KEYCLOAK_AUTH_MANAGER__REALM: "{{ .AIRFLOW__KEYCLOAK_AUTH_MANAGER__REALM.Value }}"
          AIRFLOW__KEYCLOAK_AUTH_MANAGER__SERVER_URL: "{{ .AIRFLOW__KEYCLOAK_AUTH_MANAGER__SERVER_URL.Value }}"
          AIRFLOW__API__BASE_URL: "{{ .AIRFLOW__API__BASE_URL.Value }}"
          FORWARDED_ALLOW_IPS: "{{ .FORWARDED_ALLOW_IPS.Value }}"
