---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pg-authentik-internal-certificate
  namespace: authentik
  labels:
    cnpg.io/reload: ""
spec:
  secretName: pg-authentik-internal-tls
  duration: 8760h # 1 year
  renewBefore: 720h # 30 days
  subject:
    organizations:
      - raulstechtips
  dnsNames:
    - pg-authentik-rw
    - pg-authentik-rw.authentik
    - pg-authentik-rw.authentik.svc
    - pg-authentik-rw.authentik.svc.cluster.local
    - pg-authentik-ro
    - pg-authentik-ro.authentik
    - pg-authentik-ro.authentik.svc
    - pg-authentik-ro.authentik.svc.cluster.local
    - pg-authentik-r
    - pg-authentik-r.authentik
    - pg-authentik-r.authentik.svc
    - pg-authentik-r.authentik.svc.cluster.local
  issuerRef:
    name: raulstechtips-internal-ca-issuer
    kind: ClusterIssuer
