---
name: Bug Report
description: Report a bug in the cluster configuration
title: "[BUG]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: A clear and concise description of the issue you encountered and what the expected behavior should be.
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Affected Component
      description: Which component/application is affected by this bug?
      multiple: true
      options:
        - Authentik
        - Traefik
        - Infisical
        - Longhorn
        - Cert-Manager
        - Minio
        - Redis
        - CNPG (CloudNative PostgreSQL)
        - Other
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      description: How do you trigger this bug?
      placeholder: |
        1. Go to '...'
        2. Apply the manifest '....'
        3. Check the pod status '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        Examples:
          - **Kubernetes Version**: 1.28.0
          - **Cluster Type**: k3s, RKE2, EKS, etc.
          - **Application Version**: authentik 2023.5.1
      value: |
        - Kubernetes Version:
        - Cluster Type:
        - Application Version:
    validations:
      required: false

  - type: checkboxes
    id: additional-info
    attributes:
      label: Additional Information
      description: Mark the following statements as applicable.
      options:
        - label: This issue is causing service outage
        - label: This issue is related to a recent change
        - label: I can provide a patch or PR for this issue
