---
name: Security Issue
description: Report a security concern or vulnerability
title: "[SECURITY]: "
labels: ["security", "sensitive"]
body:
  - type: markdown
    attributes:
      value: |
        ## IMPORTANT
        For critical security vulnerabilities, please follow responsible disclosure practices and contact the repository maintainers directly instead of creating a public issue.

        Use this template only for non-critical security concerns that should be tracked publicly.

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this security issue?
      multiple: false
      options:
        - Low (minor concern, no immediate threat)
        - Medium (potential risk but not easily exploitable)
        - High (significant vulnerability requiring attention)
        - Critical (immediate attention required - consider direct contact instead)
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Affected Component
      description: Which component/application is affected?
      multiple: true
      options:
        - Authentik
        - Traefik
        - Infisical
        - Longhorn
        - Cert-Manager
        - Minio
        - Redis
        - CNPG (CloudNative PostgreSQL)
        - Cluster-wide Configuration
        - Secrets Management
        - Other
    validations:
      required: true

  - type: dropdown
    id: type
    attributes:
      label: Issue Type
      description: What type of security issue is this?
      multiple: false
      options:
        - Configuration Weakness
        - Out-of-date Component with Known Vulnerability
        - Access Control Issue
        - Secret Management Issue
        - Network Exposure
        - Authentication/Authorization Concern
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the security issue in detail
      placeholder: The security concern is...
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Potential Impact
      description: What is the potential impact if this issue is exploited?
      placeholder: If exploited, this could lead to...
    validations:
      required: true

  - type: textarea
    id: mitigation
    attributes:
      label: Suggested Mitigation
      description: Do you have suggestions for mitigating this issue?
      placeholder: To mitigate this issue, we should...
    validations:
      required: false

  - type: checkboxes
    id: additional-info
    attributes:
      label: Additional Information
      options:
        - label: This issue is publicly known/disclosed
        - label: CVE or other reference is available (please include in description)
        - label: I have confirmed this is reproducible in the current environment
