---
additionalArguments:
  - --serversTransport.insecureSkipVerify=true
  - --log.level=DEBUG
  - --entryPoints.redis.address=:6379/tcp
  - --entryPoints.postgres.address=:5432/tcp
deployment:
  additionalContainers: []
  annotations: {}
  enabled: true
  initContainers: []
  podAnnotations: {}
  replicas: 3
globalArguments:
  - --global.sendanonymoususage=false
  - --global.checknewversion=false
ingressRoute:
  dashboard:
    enabled: false
ports:
  postgres:
    expose:
      default: true
    exposedPort: 5432
    port: 5432
    protocol: TCP
    tls:
      enabled: true
  redis:
    expose:
      default: true
    exposedPort: 6379
    port: 6379
    protocol: TCP
    tls:
      enabled: false
  web:
    redirections:
      entrypoint:
        priority: 10
        to: websecure
  websecure:
    advertisedPort: 4443
    http3:
      enabled: true
    tls:
      enabled: true
providers:
  kubernetesCRD:
    allowCrossNamespace: true
    allowExternalNameServices: true
    enabled: true
    ingressClass: traefik-external
  kubernetesIngress:
    allowExternalNameServices: true
    enabled: true
    publishedService:
      enabled: false
rbac:
  enabled: true
service:
  annotations: {}
  enabled: true
  externalIPs: []
  labels: {}
  loadBalancerSourceRanges: []
  spec:
    loadBalancerIP: "${TRAEFIK_LOAD_BALANCER_IP}"
  type: LoadBalancer
