---
additionalArguments:
  - --serversTransport.insecureSkipVerify=true
  - --entryPoints.redis.address=:6379/tcp
  - --entryPoints.postgres.address=:5432/tcp
logs:
  level: DEBUG
  access:
    enabled: true
    format: json
    fields:
      general:
        defaultMode: drop
        names:
          ClientAddr: keep
          RequestHost: keep
          RouterName: keep
          ServiceName: keep
          RequestPath: keep
          DownstreamStatus: keep
          OriginStatus: keep
          TLSVersion: keep
          TLSCipher: keep
          OriginDuration: keep
          Duration: keep
          RequestProtocol: keep
          RetryAttempts: keep
      headers:
        defaultMode: drop
        names:
          User-Agent: keep
          Host: keep

deployment:
  additionalContainers: []
  annotations: {}
  enabled: true
  initContainers: []
  podAnnotations: {}
  replicas: 3
globalArguments:
  - --global.sendanonymoususage=false
  - --global.checknewversion=false
ingressRoute:
  dashboard:
    enabled: false
ports:
  postgres:
    expose:
      default: true
    exposedPort: 5432
    port: 5432
    protocol: TCP
    tls:
      enabled: true
  redis:
    expose:
      default: true
    exposedPort: 6379
    port: 6379
    protocol: TCP
    tls:
      enabled: false
  web:
    redirections:
      entrypoint:
        priority: 10
        to: websecure
  websecure:
    advertisedPort: 4443
    http3:
      enabled: true
    tls:
      enabled: true
    forwardedHeaders:
      trustedIPs:
        - 173.245.48.0/20
        - 103.21.244.0/22
        - 103.22.200.0/22
        - 103.31.4.0/22
        - 141.101.64.0/18
        - 108.162.192.0/18
        - 190.93.240.0/20
        - 188.114.96.0/20
        - 197.234.240.0/22
        - 198.41.128.0/17
        - 162.158.0.0/15
        - 104.16.0.0/13
        - 104.24.0.0/14
        - 172.64.0.0/13
        - 131.0.72.0/22
providers:
  kubernetesCRD:
    allowCrossNamespace: true
    allowExternalNameServices: true
    enabled: true
    ingressClass: traefik-external
  kubernetesIngress:
    allowExternalNameServices: true
    enabled: true
    publishedService:
      enabled: false
rbac:
  enabled: true
service:
  annotations: {}
  enabled: true
  externalIPs: []
  labels: {}
  loadBalancerSourceRanges: []
  spec:
    externalTrafficPolicy: Local
    loadBalancerIP: "${ARGOCD_ENV_TRAEFIK_LOAD_BALANCER_IP}"
  type: LoadBalancer
