---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tenant-authentik
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://operator.min.io/
      chart: minio/tenant
      targetRevision: 7.1.1
      helm:
        releaseName: tenant-authentik
        namespace: authentik
        valuesFiles:
          - values/prod.yaml
      plugin:
        name: helm-envsubst-v1
        env:
          - name: S3_AUTENTHIK_PROD_DOMAIN
            valueFrom:
              secretKeyRef:
                name: argocd-app-env
                key: S3_AUTENTHIK_PROD_DOMAIN
          - name: S3_AUTENTHIK_PROD_API_DOMAIN
            valueFrom:
              secretKeyRef:
                name: argocd-app-env
                key: S3_AUTENTHIK_PROD_API_DOMAIN
    - repoURL: https://github.com/raulstechtips/cluster-config.git
      targetRevision: "6-feature-authentik-with-argocd"
      path: apps/tenant-authentik/manifests/
      plugin:
        name: kustomize-envsubst-v1
        env:
          - name: S3_AUTENTHIK_PROD_DOMAIN
            valueFrom:
              secretKeyRef:
                name: argocd-app-env
                key: S3_AUTENTHIK_PROD_DOMAIN
          - name: S3_AUTENTHIK_PROD_API_DOMAIN
            valueFrom:
              secretKeyRef:
                name: argocd-app-env
                key: S3_AUTENTHIK_PROD_API_DOMAIN
          - name: INFISICAL_PROD_HOST_API
            valueFrom:
              secretKeyRef:
                name: argocd-app-env
                key: INFISICAL_PROD_HOST_API

  destination:
    server: https://kubernetes.default.svc
    namespace: authentik
  syncPolicy: {}
  revisionHistoryLimit: 10
