---
apiVersion: v1
kind: Secret
metadata:
  name: infisical-redis-admin-credentials-secret
  namespace: infisical
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "infisical-dev"
type: Opaque
data:
  redis-password: "aW5maXNpY2FsLXBnLWFkbWlu"
