---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: minio

helmCharts:
  - name: tenant
    repo: https://operator.min.io
    version: 7.1.1
    releaseName: tenant-s3
    namespace: minio
    valuesFile: values/prod.yaml

resources:
  - manifests/secrets/secret-minio-tenant-s3-root-credentials.yaml
  - manifests/secrets/secret-minio-tenant-s3-admin-console-user-credentials.yaml
  - manifests/ingress/prod.yaml
  - manifests/certificates/tls-certificate-minio-tenant-s3.yaml
