---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: authentik-pg-admin-managed-credentials
  namespace: authentik
  labels:
    cnpg.io/reload: "true"
spec:
  hostAPI: "${INFISICAL_HOST_API}"
  authentication:
    universalAuth:
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: infisical
      secretsScope:
        projectSlug: "${INFISICAL_PROJECT_SLUG}"
        envSlug: "${INFISICAL_ENV_SLUG}"
        secretsPath: "/authentik/postgres"
        recursive: true
  managedKubeSecretReferences:
    - secretName: authentik-pg-admin-credentials-secret
      secretNamespace: authentik
      secretType: kubernetes.io/basic-auth
      creationPolicy: Owner
      template:
        includeAllSecrets: true
        data:
          username: "{{ .username.Value }}"
          password: "{{ .password.Value }}"
