---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: infisical-secret-grafana-app-secrets
  namespace: monitoring
spec:
  hostAPI: "${ARGOCD_ENV_INFISICAL_PROD_HOST_API}"
  authentication:
    universalAuth:
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: infisical
      secretsScope:
        projectSlug: "${ARGOCD_ENV_INFISICAL_PROJECT_SLUG}"
        envSlug: "${ARGOCD_ENV_INFISICAL_ENV_SLUG}"
        secretsPath: "/prometheus/grafana/app"
        recursive: true
  managedKubeSecretReferences:
    - secretName: grafana-app-secrets
      secretNamespace: monitoring
      secretType: Opaque
      creationPolicy: Owner
      template:
        includeAllSecrets: false
        data:
          # Grafana Database Configuration
          GF_DATABASE_HOST: "{{ .GF_DATABASE_HOST.Value }}:{{ .GF_DATABASE_PORT.Value }}"
          GF_DATABASE_NAME: "{{ .GF_DATABASE_NAME.Value }}"
          GF_DATABASE_USER: "{{ .GF_DATABASE_USER.Value }}"
          GF_DATABASE_PASSWORD: "{{ .GF_DATABASE_PASSWORD.Value }}"
          GF_DATABASE_SSL_MODE: "{{ .GF_DATABASE_SSL_MODE.Value }}"
          GF_DATABASE_CA_CERT_PATH: "{{ .GF_DATABASE_CA_CERT_PATH.Value }}"

          # # Grafana Remote Cache Configuration
          GF_REMOTE_CACHE_REDIS: "addr={{ .GRAFANA_REDIS_HOST.Value }},password={{ .GRAFANA_REDIS_PASSWORD.Value }}"

          # Grafana Generic OAuth Configuration
          GF_GENERIC_OAUTH_CLIENT_ID: "{{ .GF_GENERIC_OAUTH_CLIENT_ID.Value }}"
          GF_GENERIC_OAUTH_CLIENT_SECRET: "{{ .GF_GENERIC_OAUTH_CLIENT_SECRET.Value }}"
          GF_GENERIC_OAUTH_AUTH_URL: "{{ .GF_GENERIC_OAUTH_AUTH_URL.Value }}"
          GF_GENERIC_OAUTH_TOKEN_URL: "{{ .GF_GENERIC_OAUTH_TOKEN_URL.Value }}"
          GF_GENERIC_OAUTH_API_URL: "{{ .GF_GENERIC_OAUTH_API_URL.Value }}"
