---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: infisical-secret-thanos-storage-config
  namespace: monitoring
spec:
  hostAPI: "${ARGOCD_ENV_INFISICAL_PROD_HOST_API}"
  authentication:
    universalAuth:
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: infisical
      secretsScope:
        projectSlug: "${ARGOCD_ENV_INFISICAL_PROJECT_SLUG}"
        envSlug: "${ARGOCD_ENV_INFISICAL_ENV_SLUG}"
        secretsPath: "/prometheus/thanos/s3"
        recursive: true
  managedKubeSecretReferences:
    - secretName: thanos-storage-config
      secretNamespace: monitoring
      secretType: Opaque
      creationPolicy: Owner
      template:
        includeAllSecrets: false
        data:
          objstore.yml: |
            type: S3
            config:
              bucket: "{{ .THANOS_AWS_BUCKET.Value }}"
              endpoint: "{{ .THANOS_AWS_ENDPOINT.Value }}"
              region: "{{ .THANOS_S3_REGION.Value }}"
              access_key: "{{ .THANOS_AWS_ACCESS_KEY_ID.Value }}"
              secret_key: "{{ .THANOS_AWS_SECRET_ACCESS_KEY.Value }}"
