---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tenant-s3-minio-certificate
  namespace: minio
spec:
  secretName: tenant-s3-minio-tls
  duration: 8760h # 1 year
  renewBefore: 720h # 30 days
  subject:
    organizations:
      - raulstechtips
  dnsNames:
    - minio.minio
    - minio.minio.svc
    - minio.minio.svc.cluster.local
    - '*.tenant-s3-hl.minio.svc.cluster.local'
    - '*.minio.svc.cluster.local'
    - '*.tenant-s3.minio.minio.svc.cluster.local'
  issuerRef:
    name: raulstechtips-internal-ca-issuer
    kind: ClusterIssuer
