---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traefik

helmCharts:
  - name: traefik
    repo: https://traefik.github.io/charts
    version: 35.2.0
    releaseName: traefik
    namespace: traefik
    valuesFile: values/prod.yaml

resources:
  - manifests/ingress/prod.yaml
  - manifests/middleware/middleware-default-headers.yaml
  - manifests/middleware/middleware-secret-traefik-dashboard-auth-credentials.yaml
  - manifests/middleware/middleware-vpn-ip-acl.yaml
  - manifests/secrets/secret-traefik-dashboard-auth-credentials.yaml
