---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: infisical-secret-pg-harbor-database-credentials
  namespace: prod
spec:
  hostAPI: "${ARGOCD_ENV_INFISICAL_PROD_HOST_API}"
  authentication:
    universalAuth:
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: infisical
      secretsScope:
        projectSlug: "${ARGOCD_ENV_INFISICAL_PROJECT_SLUG}"
        envSlug: "${ARGOCD_ENV_INFISICAL_ENV_SLUG}"
        secretsPath: "/harbor/postgres"
        recursive: true
  managedKubeSecretReferences:
    - secretName: pg-harbor-database-credentials-secret
      secretNamespace: prod
      secretType: kubernetes.io/basic-auth
      creationPolicy: Owner
      template:
        includeAllSecrets: false
        data:
          username: "{{ .PG_HARBOR_ADMIN_USERNAME.Value }}"
          password: "{{ .PG_HARBOR_ADMIN_PASSWORD.Value }}"
