---
apiVersion: v1
kind: Secret
metadata:
  name: pg-infisical-database-credentials-secret
  namespace: prod
  labels:
    cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
  username: ${ARGOCD_ENV_INFISICAL_PG_ADMIN_USERNAME}
  password: ${ARGOCD_ENV_INFISICAL_PG_ADMIN_PASSWORD}
secretTemplate:
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "prod,infisical"
