---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: infisical-secret-pg-sdpm-database-credentials
  namespace: prod
  labels:
    cnpg.io/reload: "true"
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "sdpm"
spec:
  hostAPI: "${ARGOCD_ENV_INFISICAL_PROD_HOST_API}"
  authentication:
    universalAuth:
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: infisical
      secretsScope:
        projectSlug: "${ARGOCD_ENV_INFISICAL_PROJECT_SLUG}"
        envSlug: "${ARGOCD_ENV_INFISICAL_ENV_SLUG}"
        secretsPath: "/sdpm/database"
        recursive: true
  managedKubeSecretReferences:
    - secretName: pg-sdpm-database-credentials-secret
      secretNamespace: prod
      secretType: kubernetes.io/basic-auth
      creationPolicy: Owner
      template:
        includeAllSecrets: false
        data:
          username: "{{ .PG_SDPM_USER.Value }}"
          password: "{{ .PG_SDPM_PASSWORD.Value }}"
