---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: longhorn-manager
  namespace: longhorn-system
spec:
  template:
    spec:
      containers:
        - name: longhorn-manager
          env:
            - name: GODEBUG
              value: "tlsrsakex=1,tls10server=1,tlsunsafeekm=1,tlsmlkem=0,http2debug=2,http1debug=2,tlsdebug=1,x509roots=1"
