---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-default-storage-class
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Retain
parameters:
  numberOfReplicas: "3"
  staleReplicaTimeout: "1440" # 24 hours in minutes
  volumeExpansion: "true"
