---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-storage-class-replicas-1
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Retain
parameters:
  numberOfReplicas: "1"
  staleReplicaTimeout: "1440" # 24 hours in minutes
  volumeExpansion: "true"
