---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalPushSecret
metadata:
  name: infisical-push-secret-live-tls
spec:
  hostAPI: "${ARGOCD_ENV_INFISICAL_PROD_HOST_API}"
  updatePolicy: Replace
  resyncInterval: 1m
  authentication:
    universalAuth:
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: infisical
  destination:
    projectId: "${ARGOCD_ENV_INFISICAL_PROJECT_ID}"
    environmentSlug: "${ARGOCD_ENV_INFISICAL_ENV_SLUG}"
    secretsPath: "/keycloak/tls"
  push:
    secret:
      secretName: live-raulstechtips-tls
      secretNamespace: keycloak
      template:
        includeAllSecrets: false
        data:
          KEYCLOAK_LIVE_TLS_CRT: "{{ (index . \"tls.crt\").Value }}"
          KEYCLOAK_LIVE_TLS_KEY: "{{ (index . \"tls.key\").Value }}"
