---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-infisical
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/raulstechtips/cluster-config.git
    targetRevision: refs/heads/8-feature-migrate-infisical-to-argocd
    path: apps/infisical
    plugin:
      name: kustomize-envsubst
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy: {}
  revisionHistoryLimit: 10
