---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev

helmCharts:
  - name: infisical-standalone
    repo: https://dl.cloudsmith.io/public/infisical/helm-charts/helm/charts/
    version: 1.5.0
    releaseName: infisical-dev
    namespace: dev
    valuesFile: values/dev.yaml

resources:
  - manifests/ingress/dev.yaml
  - manifests/secrets/infisical-secrets.yaml

patches:
  - target:
      kind: Deployment
      name: infisical-dev-infisical-standalone-infisical-dev
    path: manifests/overlays/deployment-patch.yaml
  - target:
      kind: Job
      name: infisical-dev-schema-migration-1
    path: manifests/overlays/migration-job-patch.yaml
