---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: infisical-secret-harbor-registry-secret
  namespace: harbor
spec:
  hostAPI: "${ARGOCD_ENV_INFISICAL_PROD_HOST_API}"
  authentication:
    universalAuth:
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: infisical
      secretsScope:
        projectSlug: "${ARGOCD_ENV_INFISICAL_PROJECT_SLUG}"
        envSlug: "${ARGOCD_ENV_INFISICAL_ENV_SLUG}"
        secretsPath: "/harbor/registry"
        recursive: true
  managedKubeSecretReferences:
    - secretName: harbor-registry-secret-v1
      secretNamespace: harbor
      secretType: Opaque
      creationPolicy: Owner
      template:
        includeAllSecrets: false
        data:
          REGISTRY_PASSWD: "{{ .HARBOR_REGISTRY_PASSWD.Value }}"
          REGISTRY_HTPASSWD: "{{ .HARBOR_REGISTRY_HTPASSWD.Value }}"
