---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: infisical-secret-harbor-admin-credentials-secret
  namespace: harbor
spec:
  hostAPI: "${ARGOCD_ENV_INFISICAL_PROD_HOST_API}"
  authentication:
    universalAuth:
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: infisical
      secretsScope:
        projectSlug: "${ARGOCD_ENV_INFISICAL_PROJECT_SLUG}"
        envSlug: "${ARGOCD_ENV_INFISICAL_ENV_SLUG}"
        secretsPath: "/harbor/app"
        recursive: true
  managedKubeSecretReferences:
    - secretName: harbor-admin-credentials-secret
      secretNamespace: harbor
      secretType: Opaque
      creationPolicy: Owner
      template:
        includeAllSecrets: false
        data:
          HARBOR_ADMIN_PASSWORD: "{{ .HARBOR_ADMIN_PASSWORD.Value }}"
