---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-prod
  namespace: prod
  labels:
    cnpg.io/reload: ""
spec:
  description: "Prod PostgreSQL Cluster"
  instances: 3
  affinity:
    podAntiAffinityType: required
  primaryUpdateStrategy: unsupervised
  enableSuperuserAccess: true
  postgresql:
    parameters:
      max_wal_size: "16GB"
      max_slot_wal_keep_size: "16GB"
      # connection settings
      max_connections: "500"  # Should be > (max_db_connections × pooler_instances + buffer)
      # Other important settings
      shared_buffers: "256MB"  # Adjust based on your resources
      work_mem: "4MB"  # Per-connection work memory
  certificates:
    serverCASecret: raulstechtips-internal-ca-key-pair
    serverTLSSecret: pg-prod-internal-tls
  bootstrap:
    initdb:
      database: prod
      owner: pg-prod-admin
      secret:
        name: pg-prod-admin-credentials-secret
  backup:
    retentionPolicy: '7d'
    volumeSnapshot:
      className: longhorn-volume-snapshot-class
      walClassName: longhorn-volume-snapshot-class
      snapshotOwnerReference: none
  storage:
    storageClass: longhorn-storage-class-local
    size: 20Gi
  walStorage:
    storageClass: longhorn-storage-class-local
    size: 20Gi
  managed:
    roles:
      - name: pg-grafana
        comment: "Grafana Database"
        ensure: present
        passwordSecret:
          name: pg-grafana-database-credentials-secret
        createdb: true
        login: true
        superuser: false
      - name: pg-coder
        comment: "Coder Database"
        ensure: present
        passwordSecret:
          name: pg-coder-database-credentials-secret
        createdb: true
        login: true
        superuser: false
      - name: pg-harbor-admin
        comment: "Harbor Database"
        ensure: present
        passwordSecret:
          name: pg-harbor-database-credentials-secret
        createdb: true
        login: true
        superuser: false
      - name: infisical-pg-admin
        comment: "Infisical Database"
        ensure: present
        passwordSecret:
          name: pg-infisical-database-credentials-secret
        createdb: true
        login: true
        superuser: false
      - name: pg-keycloak-admin
        comment: "Keycloak Database"
        ensure: present
        passwordSecret:
          name: pg-keycloak-database-credentials-secret
        createdb: true
        login: true
        superuser: false
      - name: pg-sdpm-admin
        comment: "SDPM Database"
        ensure: present
        passwordSecret:
          name: pg-sdpm-database-credentials-secret
        createdb: true
        login: true
        superuser: false
