---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: minio-operator

helmCharts:
  - name: operator
    repo: https://operator.min.io
    version: 7.0.1
    releaseName: minio-operator
    namespace: minio-operator
    valuesFile: values/prod.yaml

resources:
  - manifests/certificates/tls-certificate-sts.yaml
  - manifests/secrets/secret-minio-operator-ca-tls-tenant-authentik.yaml
