apiVersion: traefik.io/v1alpha1
kind: TLSOption
metadata:
  name: no-alpn
  namespace: longhorn-system
spec:
  alpnProtocols:
    - http/1.1
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: minio-ingress
  namespace: minio
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`${ARGOCD_ENV_S3_PROD_DOMAIN}`)
      kind: Rule
      middlewares:
        - name: default-headers
          namespace: default
      services:
        - name: tenant-s3-console
          port: 9443
    - match: Host(`${ARGOCD_ENV_S3_PROD_API_DOMAIN}`)
      kind: Rule
      middlewares:
        - name: default-headers
          namespace: default
      services:
        - name: minio
          port: 443
  tls:
    secretName: prod-raulstechtips-tls
    options:
      name: no-alpn
