---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gha-runner-scale-set
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/raulstechtips/cluster-config.git
    targetRevision: feature/github-action-runners
    path: apps/arc-runners
    plugin:
      name: kustomize-envsubst
  destination:
    server: https://kubernetes.default.svc
    namespace: arc-runners
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
  revisionHistoryLimit: 10
