---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: authentik-minio-ingress
  namespace: authentik
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`${S3_AUTHENTIK_PROD_DOMAIN}`)
      kind: Rule
      middlewares:
        - name: default-headers
          namespace: default
      services:
        - name: tenant-authentik-console
          port: 9443
    - match: Host(`${S3_AUTHENTIK_PROD_DOMAIN}`)
      kind: Rule
      middlewares:
        - name: default-headers
          namespace: default
      services:
        - name: minio
          port: 443
  tls:
    secretName: prod-raulstechtips-tls
