---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: pg-huginn
  namespace: dev
spec:
  databaseReclaimPolicy: delete
  name: pg-huginn
  owner: pg-huginn-admin
  allowConnections: true
  cluster:
    name: pg-dev
