---
apiVersion: v1
kind: Secret
metadata:
  name: infisical-pg-admin-credentials-secret
  namespace: dev
  labels:
    cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
  username: "${ARGOCD_ENV_INFISICAL_PG_ADMIN_USERNAME}"
  password: "${ARGOCD_ENV_INFISICAL_PG_ADMIN_PASSWORD}"
