---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: infisical-secret-argocd-harbor-secrets
  namespace: argocd
spec:
  resyncInterval: 60
  hostAPI: "${ARGOCD_ENV_INFISICAL_PROD_HOST_API}"
  authentication:
    universalAuth:
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: infisical
      secretsScope:
        projectSlug: "${ARGOCD_ENV_INFISICAL_PROJECT_SLUG}"
        envSlug: "${ARGOCD_ENV_INFISICAL_ENV_SLUG}"
        secretsPath: "/harbor"
        recursive: true
  managedKubeSecretReferences:
    - secretName: argocd-harbor-secrets
      secretNamespace: argocd
      secretType: Opaque
      creationPolicy: Owner
      template:
        includeAllSecrets: false
        data:
          ARGOCD_ENV_INFISICAL_PG_HARBOR_PASSWORD: "{{ .PG_HARBOR_ADMIN_PASSWORD.Value }}"
          ARGOCD_ENV_INFISICAL_REDIS_PASSWORD: "{{ .HARBOR_REDIS_PASSWORD.Value }}"
