---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalPushSecret
metadata:
  name: infisical-push-secret-tenant-s3-minio-tls
spec:
  hostAPI: ${ARGOCD_ENV_INFISICAL_PROD_HOST_API}
  updatePolicy: Replace
  resyncInterval: 1m
  authentication:
    universalAuth:
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: infisical
  destination:
    projectId: ${ARGOCD_ENV_INFISICAL_PROJECT_ID}
    environmentSlug: prod
    secretsPath: "/certificates/internal"
  push:
    secret:
      secretName: raulstechtips-internal-ca-key-pair
      secretNamespace: minio-operator
      template:
        includeAllSecrets: true
