---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: infisical-secret-operator-ca-tls-tenant-authentik
  namespace: minio-operator
spec:
  hostAPI: "${ARGOCD_ENV_INFISICAL_HOST_API}"
  authentication:
    universalAuth:
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: infisical
      secretsScope:
        projectSlug: "${ARGOCD_ENV_INFISICAL_PROJECT_SLUG}"
        envSlug: "${ARGOCD_ENV_INFISICAL_ENV_SLUG}"
        secretsPath: "/certificates/internal"
        recursive: true
  managedKubeSecretReferences:
    - secretName: operator-ca-tls-tenant-authentik
      secretNamespace: minio-operator
      secretType: Opaque
      creationPolicy: Owner
      template:
        includeAllSecrets: true
