---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: infisical-secret-jenkins-github-app
  namespace: jenkins
spec:
  hostAPI: ${ARGOCD_ENV_INFISICAL_PROD_HOST_API}
  authentication:
    universalAuth:
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: infisical
      secretsScope:
        projectSlug: ${ARGOCD_ENV_INFISICAL_PROJECT_SLUG}
        envSlug: ${ARGOCD_ENV_INFISICAL_ENV_SLUG}
        secretsPath: "/jenkins"
        recursive: true
  managedKubeSecretReferences:
    - secretName: jenkins-github-app-raulstechtips
      secretNamespace: jenkins
      secretType: Opaque
      creationPolicy: Owner
      template:
        includeAllSecrets: false
        data:
          owner: "{{ .GITHUB_APP_OWNER.Value }}"
          appId: "{{ .GITHUB_APP_ID.Value }}"
          privateKey: "{{ .GITHUB_APP_PRIVATE_KEY.Value }}"
          pat: "{{ .GITHUB_APP_PAT.Value }}"
