---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: infisical-secret-jenkins-admin-credentials
  namespace: jenkins
spec:
  hostAPI: ${ARGOCD_ENV_INFISICAL_PROD_HOST_API}
  authentication:
    universalAuth:
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: infisical
      secretsScope:
        projectSlug: ${ARGOCD_ENV_INFISICAL_PROJECT_SLUG}
        envSlug: ${ARGOCD_ENV_INFISICAL_ENV_SLUG}
        secretsPath: "/jenkins"
        recursive: true
  managedKubeSecretReferences:
    - secretName: jenkins-admin-credentials
      secretNamespace: jenkins
      secretType: Opaque
      creationPolicy: Owner
      template:
        includeAllSecrets: false
        data:
          jenkins-admin-user: "{{ .JENKINS_ADMIN_USER.Value }}"
          jenkins-admin-password: "{{ .JENKINS_ADMIN_PASSWORD.Value }}"
