---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: infisical-secret-jenkins-kube-config
  namespace: jenkins
spec:
  hostAPI: ${INFISICAL_HOST_API}
  authentication:
    universalAuth:
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: infisical
      secretsScope:
        projectSlug: ${INFISICAL_PROJECT_SLUG}
        envSlug: ${INFISICAL_ENV_SLUG}
        secretsPath: "/kubeconfig"
        recursive: true
  managedKubeSecretReferences:
    - secretName: jenkins-kube-config
      secretNamespace: jenkins
      secretType: Opaque
      creationPolicy: Owner
      template:
        includeAllSecrets: false
        data:
          config: "{{ .KUBE_CONFIG.Value }}"
