---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: jenkins-admin-credentials
  namespace: jenkins
  labels:
    cnpg.io/reload: "true"
spec:
  hostAPI: ${INFISICAL_HOST_API}
  authentication:
    universalAuth:
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: infisical
      secretsScope:
        projectSlug: ${INFISICAL_PROJECT_SLUG}
        envSlug: ${INFISICAL_ENV_SLUG}
        secretsPath: "/jenkins"
        recursive: true
  managedKubeSecretReferences:
    - secretName: jenkins-admin-credentials-secret
      secretNamespace: jenkins
      secretType: Opaque
      creationPolicy: Owner
      template:
        includeAllSecrets: false
        data:
          username: "{{ .ADMIN_USERNAME.Value }}"
          password: "{{ .ADMIN_PASSWORD.Value }}"
