---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: infisical-secret-infisical-smtp-secret
  namespace: infisical
spec:
  hostAPI: "${ARGOCD_ENV_INFISICAL_PROD_HOST_API}"
  authentication:
    universalAuth:
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: infisical
      secretsScope:
        projectSlug: "${ARGOCD_ENV_INFISICAL_PROJECT_SLUG}"
        envSlug: "${ARGOCD_ENV_INFISICAL_ENV_SLUG}"
        secretsPath: "/infisical/smtp"
        recursive: true
  managedKubeSecretReferences:
    - secretName: infisical-smtp-secret
      secretNamespace: infisical
      secretType: Opaque
      creationPolicy: Owner
      template:
        includeAllSecrets: false
        data:
          SMTP_FROM_ADDRESS: "{{ .SMTP_FROM_ADDRESS.Value }}"
          SMTP_FROM_NAME: "{{ .SMTP_FROM_NAME.Value }}"
          SMTP_HELO_HOST: "{{ .SMTP_HELO_HOST.Value }}"
          SMTP_HOST: "{{ .SMTP_HOST.Value }}"
          SMTP_PASSWORD: "{{ .SMTP_PASSWORD.Value }}"
          SMTP_USERNAME: "{{ .SMTP_USERNAME.Value }}"
