---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: jenkins-ingress-live
  namespace: jenkins
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`${ARGOCD_ENV_JENKINS_LIVE_DOMAIN}`)
      kind: Rule
      middlewares:
        - name: github-hooks-ips
          namespace: jenkins
        - name: vpn-ip-acl
          namespace: default
        - name: default-headers
          namespace: default
      services:
        - name: jenkins
          port: 8080
  tls:
    secretName: live-raulstechtips-tls
