---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: jenkins-ingress
  namespace: jenkins
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`${ARGOCD_ENV_JENKINS_PROD_DOMAIN}`)
      kind: Rule
      middlewares:
        - name: default-headers
          namespace: default
      services:
        - name: jenkins
          port: 8080
  tls:
    secretName: prod-raulstechtips-tls
