---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: infisical-secret-keycloak-admin-credentials
  namespace: keycloak
spec:
  hostAPI: "${ARGOCD_ENV_INFISICAL_PROD_HOST_API}"
  authentication:
    universalAuth:
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: infisical
      secretsScope:
        projectSlug: "${ARGOCD_ENV_INFISICAL_PROJECT_SLUG}"
        envSlug: "${ARGOCD_ENV_INFISICAL_ENV_SLUG}"
        secretsPath: "/keycloak/admin"
        recursive: true
  managedKubeSecretReferences:
    - secretName: keycloak-admin-credentials-secret
      secretNamespace: keycloak
      secretType: Opaque
      creationPolicy: Owner
      template:
        includeAllSecrets: false
        data:
          KEYCLOAK_ADMIN_PASSWORD: "{{ .KEYCLOAK_ADMIN_PASSWORD.Value }}"
