---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: authentik-ingress
  namespace: authentik
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`${ARGOCD_ENV_AUTHENTIK_PROD_DOMAIN}`)
      kind: Rule
      priority: 10
      middlewares:
        - name: default-headers
          namespace: default
      services:
        - name: authentik-server
          port: 443
    - match: Host(`*.${ARGOCD_ENV_AUTHENTIK_PROD_DOMAIN}`) && PathPrefix(`/outpost.goauthentik.io/`)
      kind: Rule
      priority: 15
      middlewares:
        - name: default-headers
          namespace: default
      services:
        - name: authentik-server
          port: 443
  tls:
    secretName: prod-raulstechtips-tls
