---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/raulstechtips/cluster-config.git
    targetRevision: HEAD
    path: apps/harbor
    plugin:
      name: kustomize-envsubst
  destination:
    server: https://kubernetes.default.svc
    namespace: harbor
  syncPolicy:
    syncOptions:
      - RespectIgnoreDifferences=true
  revisionHistoryLimit: 10
  ignoreDifferences:
    - group: ""
      kind: Secret
      name: harbor-core
      jsonPointers:
        - /data
    - group: ""
      kind: Secret
      name: harbor-jobservice
      jsonPointers:
        - /data
    - group: ""
      kind: Secret
      name: harbor-registry
      jsonPointers:
        - /data
    - group: ""
      kind: Secret
      name: harbor-registryctl
      jsonPointers:
        - /data
    # Ignore checksum annotations on deployments (they change with config changes)
    - group: apps
      kind: Deployment
      name: harbor-core
      jsonPointers:
        - /spec/template/metadata/annotations
    - group: apps
      kind: Deployment
      name: harbor-jobservice
      jsonPointers:
        - /spec/template/metadata/annotations
    - group: apps
      kind: Deployment
      name: harbor-registry
      jsonPointers:
        - /spec/template/metadata/annotations
