---
apiVersion: v1
kind: Secret
metadata:
  name: infisical-pg-admin-credentials-secret
  namespace: infisical
  labels:
    cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
data:
  username: "${INFISICAL_PG_ADMIN_USERNAME}"
  password: "${INFISICAL_PG_ADMIN_PASSWORD}"
