---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: infisical-secret-argocd-app-env-dev
  namespace: argocd
spec:
  resyncInterval: 60
  hostAPI: "${ARGOCD_ENV_INFISICAL_PROD_HOST_API}"
  authentication:
    universalAuth:
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: infisical
      secretsScope:
        projectSlug: "${ARGOCD_ENV_INFISICAL_PROJECT_SLUG}"
        envSlug: "dev"
        secretsPath: "/argocd/apps/env"
        recursive: true
  managedKubeSecretReferences:
    - secretName: argocd-app-env-dev
      secretNamespace: argocd
      secretType: Opaque
      creationPolicy: Owner
      template:
        includeAllSecrets: false
        data:
          # ARGOCD_ENV_ARGOCD_PROD_DOMAIN: "{{ .ARGOCD_APP.Value }}.{{ .DOMAIN.Value }}"
          # ARGOCD_ENV_DOMAIN: "{{ .DOMAIN.Value }}"
          # ARGOCD_ENV_INFISICAL_PROJECT_SLUG: "{{ .INFISICAL_PROJECT_SLUG.Value }}"
          # ARGOCD_ENV_INFISICAL_ENV_SLUG: "{{ .INFISICAL_ENV_SLUG.Value }}"
          # ARGOCD_ENV_INFISICAL_PG_ADMIN_USERNAME: "{{ .INFISICAL_PG_ADMIN_USERNAME.Value }}"
          # ARGOCD_ENV_INFISICAL_PG_ADMIN_PASSWORD: "{{ .INFISICAL_PG_ADMIN_PASSWORD.Value }}"
          # ARGOCD_ENV_INFISICAL_REDIS_PASSWORD: "{{ .INFISICAL_REDIS_PASSWORD.Value }}"
          # ARGOCD_ENV_INFISICAL_ENCRYPTION_KEY: "{{ .INFISICAL_ENCRYPTION_KEY.Value }}"
          # ARGOCD_ENV_INFISICAL_AUTH_SECRET: "{{ .INFISICAL_AUTH_SECRET.Value }}"
          # ARGOCD_ENV_AUTHENTIK_PROD_DOMAIN: "{{ .AUTHENTIK_APP.Value }}.{{ .DOMAIN.Value }}"
          # ARGOCD_ENV_S3_PROD_DOMAIN: "{{ .S3_CONSOLE.Value }}.{{ .DOMAIN.Value }}"
          # ARGOCD_ENV_S3_PROD_API_DOMAIN: "{{ .S3_API.Value }}.{{ .DOMAIN.Value }}"
          # ARGOCD_ENV_LONGHORN_PROD_DOMAIN: "{{ .LONGHORN_APP.Value }}.{{ .DOMAIN.Value }}"
          # ARGOCD_ENV_TRAEFIK_PROD_DOMAIN: "{{ .TRAEFIK_APP.Value }}.{{ .DOMAIN.Value }}"
          # ARGOCD_ENV_TRAEFIK_LOAD_BALANCER_IP: "{{ .TRAEFIK_LOAD_BALANCER_IP.Value }}"
          # ARGOCD_ENV_CLOUDFLARE_EMAIL: "{{ .CLOUDFLARE_EMAIL.Value }}"
          # ARGOCD_ENV_CLOUDFLARE_API_TOKEN: "{{ .CLOUDFLARE_API_TOKEN.Value }}"
          # ARGOCD_ENV_GITHUB_HOOKS_IP: "{{ .GITHUB_HOOKS_IP.Value }}"
          # ARGOCD_ENV_JENKINS_LIVE_DOMAIN: "{{ .JENKINS_LIVE_APP.Value }}.{{ .DOMAIN.Value }}"
          # ARGOCD_ENV_JENKINS_PROD_DOMAIN: "{{ .JENKINS_APP.Value }}.{{ .DOMAIN.Value }}"
          ARGOCD_ENV_INFISICAL_DEV_DOMAIN: "{{ .INFISICAL_APP.Value }}.{{ .DOMAIN.Value }}"
          ARGOCD_ENV_INFISICAL_DEV_HOST_API: "https://{{ .INFISICAL_APP.Value }}.{{ .DOMAIN.Value }}/api"
