---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-infisical
  namespace: infisical
  labels:
    cnpg.io/reload: ""
spec:
  description: "Infisical PostgreSQL Cluster"
  instances: 3
  primaryUpdateStrategy: unsupervised
  enableSuperuserAccess: true
  certificates:
    serverCASecret: raulstechtips-internal-ca-key-pair
    serverTLSSecret: pg-infisical-internal-tls
  bootstrap:
    initdb:
      database: infisical
      owner: infisical-pg-admin
      secret:
        name: infisical-pg-admin-credentials-secret
  backup:
    retentionPolicy: '60d'
    volumeSnapshot:
      className: longhorn-pg-main-infisical
      walClassName: longhorn-pg-wal-infisical
      snapshotOwnerReference: none
  storage:
    storageClass: longhorn-pg-main-infisical
    size: 2Gi
  walStorage:
    storageClass: longhorn-pg-wal-infisical
    size: 2Gi
