---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-authentik
  namespace: authentik
  labels:
    cnpg.io/reload: ""
  annotations:
    secrets.infisical.com/auto-reload: "true"
spec:
  description: "Authentik PostgreSQL Cluster"
  instances: 3
  primaryUpdateStrategy: unsupervised
  enableSuperuserAccess: true
  certificates:
    serverCASecret: raulstechtips-internal-ca-key-pair
    serverTLSSecret: pg-authentik-internal-tls
  bootstrap:
    initdb:
      database: authentik
      owner: authentik-pg-admin
      secret:
        name: infisical-secret-authentik-pg-admin-credentials
  backup:
    retentionPolicy: '30d'
    volumeSnapshot:
      className: longhorn-volume-snapshot-class
      walClassName: longhorn-volume-snapshot-class
      snapshotOwnerReference: none
  storage:
    storageClass: longhorn-storage-class-local
    size: 20Gi
  walStorage:
    storageClass: longhorn-storage-class-local
    size: 20Gi
