---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-authentik
  namespace: authentik
  labels:
    cnpg.io/reload: ""
  annotations:
    secrets.infisical.com/auto-reload: "true"
spec:
  description: "Authentik PostgreSQL Cluster"
  instances: 3
  primaryUpdateStrategy: unsupervised
  enableSuperuserAccess: true
  certificates:
    serverCASecret: raulstechtips-internal-ca-key-pair
    serverTLSSecret: pg-authentik-internal-tls
  bootstrap:
    initdb:
      database: authentik
      owner: authentik-pg-admin
      secret:
        name: authentik-pg-admin-credentials-secret
  backup:
    retentionPolicy: '60d'
    volumeSnapshot:
      className: longhorn-pg-main-authentik
      walClassName: longhorn-pg-wal-authentik
      snapshotOwnerReference: none
  storage:
    storageClass: longhorn-pg-main-authentik
    size: 2Gi
  walStorage:
    storageClass: longhorn-pg-wal-authentik
    size: 2Gi
