---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: authentik-postgresql-scheduled-backup
  namespace: authentik
spec:
  cluster:
    name: pg-authentik
  schedule: "0 0 0 * * *"
  backupOwnerReference: none
  method: volumeSnapshot
  immediate: true
