---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: vpn-ip-acl
  namespace: traefik
spec:
  ipAllowList:
    sourceRange:
      - ${ARGOCD_ENV_VPN_IP}
      - 10.0.0.0/8 # Allow all internal K3s IPs
