---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infisical
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/raulstechtips/cluster-config.git
    targetRevision: HEAD
    path: apps/infisical
    plugin:
      name: kustomize-envsubst
  destination:
    server: https://kubernetes.default.svc
    namespace: infisical
  syncPolicy: {}
  revisionHistoryLimit: 10
  ignoreDifferences:
    - group: apps
      kind: Deployment
      name: infisical-infisical-standalone-infisical
      namespace: infisical
      jqPathExpressions:
        - .metadata.annotations.updatedAt
        - .spec.template.metadata.annotations.updatedAt
