---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: infisical

helmCharts:
  - name: infisical-standalone
    repo: https://dl.cloudsmith.io/public/infisical/helm-charts/helm/charts/
    version: 1.5.0
    releaseName: infisical
    namespace: infisical
    valuesFile: values/prod.yaml

resources:
  - manifests/ingress/prod.yaml
  - manifests/secrets/infisical-secrets.yaml

patches:
  - target:
      kind: Deployment
      name: infisical-infisical-standalone-infisical
    path: manifests/overlays/deployment-patch.yaml
  - target:
      kind: Job
      name: infisical-schema-migration-2
    path: manifests/overlays/migration-job-patch.yaml
