---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: infisical-secret-serenemind-pg-admin-credentials-secret
  namespace: serenemind
  labels:
    cnpg.io/reload: "true"
spec:
  hostAPI: "${ARGOCD_ENV_INFISICAL_PROD_HOST_API}"
  authentication:
    universalAuth:
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: infisical
      secretsScope:
        projectSlug: "${ARGOCD_ENV_INFISICAL_PROJECT_SLUG}"
        envSlug: staging
        secretsPath: "/serenemind/app"
        recursive: true
  managedKubeSecretReferences:
    - secretName: serenemind-app-secret
      secretNamespace: serenemind
      secretType: Opaque
      creationPolicy: Owner
      template:
        includeAllSecrets: false
        data:
          # Application related secrets
          APP_ENV: "{{ .APP_ENV.Value }}"
          SECRET_KEY: "{{ .SECRET_KEY.Value }}"
          ALLOWED_HOSTS: "{{ .ALLOWED_HOSTS.Value }}"
          CORS_ALLOWED_ORIGINS: "{{ .CORS_ALLOWED_ORIGINS.Value }}"
          CSRF_TRUSTED_ORIGINS: "{{ .CSRF_TRUSTED_ORIGINS.Value }}"

          SQL_HOST: "{{ .SQL_HOST.Value }}"
          SQL_DATABASE: "{{ .SQL_DATABASE.Value }}"

          DATABASE: "{{ .DATABASE.Value }}"
          AWS_STORAGE_BUCKET_NAME_STATIC: "{{ .AWS_STORAGE_BUCKET_NAME_STATIC.Value }}"
          AWS_STORAGE_BUCKET_NAME_MEDIA: "{{ .AWS_STORAGE_BUCKET_NAME_MEDIA.Value }}"
          AWS_S3_REGION_NAME: "{{ .AWS_S3_REGION_NAME.Value }}"

          # ONLY STAGING SECRETS
          AWS_S3_ENDPOINT_URL: "{{ .AWS_S3_ENDPOINT_URL.Value }}"
