---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: infisical-secret-github-registry
  namespace: serenemind
spec:
  hostAPI: "https://infisical.prod.raulstechtips.dev/api"
  authentication:
    universalAuth:
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: infisical
      secretsScope:
        projectSlug: "k3s-ntpo"
        envSlug: "serenemind"
        secretsPath: "/registry"
        recursive: true
  managedKubeSecretReferences:
    - secretName: github-registry-secret
      secretNamespace: serenemind
      secretType: Opaque
      creationPolicy: Owner
      template:
        includeAllSecrets: false
        data:
          username: "{{ .username.Value }}"
          password: "{{ .password.Value }}"
          email: "{{ .email.Value }}"
