---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: infisical-secret-serenemind-smtp-secret
  namespace: serenemind
  labels:
    cnpg.io/reload: "true"
spec:
  hostAPI: "${ARGOCD_ENV_INFISICAL_PROD_HOST_API}"
  authentication:
    universalAuth:
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: infisical
      secretsScope:
        projectSlug: "${ARGOCD_ENV_INFISICAL_PROJECT_SLUG}"
        envSlug: staging
        secretsPath: "/serenemind/smtp"
        recursive: true
  managedKubeSecretReferences:
    - secretName: serenemind-smtp-secret
      secretNamespace: serenemind
      secretType: Opaque
      creationPolicy: Owner
      template:
        includeAllSecrets: false
        data:
          EMAIL_HOST: "{{ .EMAIL_HOST.Value }}"
          EMAIL_PORT: "{{ .EMAIL_PORT.Value }}"
          EMAIL_HOST_USER: "{{ .EMAIL_HOST_USER.Value }}"
          EMAIL_HOST_PASSWORD: "{{ .EMAIL_HOST_PASSWORD.Value }}"
          DEFAULT_FROM_EMAIL: "{{ .DEFAULT_FROM_EMAIL.Value }}"
