---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: infisical-secret-oauth2-proxy-client-secret
  namespace: oauth2-proxy
spec:
  hostAPI: "${ARGOCD_ENV_INFISICAL_PROD_HOST_API}"
  authentication:
    universalAuth:
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: infisical
      secretsScope:
        projectSlug: "${ARGOCD_ENV_INFISICAL_PROJECT_SLUG}"
        envSlug: "${ARGOCD_ENV_INFISICAL_ENV_SLUG}"
        secretsPath: "/oauth2/config"
        recursive: true
  managedKubeSecretReferences:
    - secretName: oauth2-proxy-client-secret
      secretNamespace: oauth2-proxy
      secretType: Opaque
      creationPolicy: Owner
      template:
        includeAllSecrets: false
        data:
          client-id: "{{ .OAUTH2_PROXY_CLIENT_ID.Value }}"
          client-secret: "{{ .OAUTH2_PROXY_CLIENT_SECRET.Value }}"
          cookie-secret: "{{ .OAUTH2_PROXY_COOKIE_SECRET.Value }}"
