---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: infisical-secret-oauth2-proxy-config-secret
  namespace: oauth2-proxy
spec:
  hostAPI: "${ARGOCD_ENV_INFISICAL_PROD_HOST_API}"
  authentication:
    universalAuth:
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: infisical
      secretsScope:
        projectSlug: "${ARGOCD_ENV_INFISICAL_PROJECT_SLUG}"
        envSlug: "${ARGOCD_ENV_INFISICAL_ENV_SLUG}"
        secretsPath: "/oauth2/config"
        recursive: true
  managedKubeSecretReferences:
    - secretName: oauth2-proxy-config-secret
      secretNamespace: oauth2-proxy
      secretType: Opaque
      creationPolicy: Owner
      template:
        includeAllSecrets: false
        data:
          OAUTH2_PROXY_PROVIDER: "{{ .OAUTH2_PROXY_PROVIDER.Value }}"
          OAUTH2_PROXY_OIDC_ISSUER_URL: "{{ .OAUTH2_PROXY_OIDC_ISSUER_URL.Value }}"
          OAUTH2_PROXY_REDIRECT_URL: "{{ .OAUTH2_PROXY_REDIRECT_URL.Value }}"
          OAUTH2_PROXY_COOKIE_DOMAINS: "{{ .OAUTH2_PROXY_COOKIE_DOMAINS.Value }}"
          OAUTH2_PROXY_WHITELIST_DOMAINS: "{{ .OAUTH2_PROXY_WHITELIST_DOMAINS.Value }}"
          OAUTH2_PROXY_EMAIL_DOMAINS: "{{ .OAUTH2_PROXY_EMAIL_DOMAINS.Value }}"
          OAUTH2_PROXY_ALLOWED_GROUP: "{{ .OAUTH2_PROXY_ALLOWED_GROUP.Value }}"
