---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: keycloak
  namespace: prod
spec:
  databaseReclaimPolicy: delete
  name: keycloak
  owner: pg-keycloak-admin
  allowConnections: true
  cluster:
    name: pg-prod
