---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: pg-sdpm
  namespace: prod
spec:
  databaseReclaimPolicy: delete
  name: pg-sdpm
  owner: pg-sdpm-admin
  allowConnections: true
  cluster:
    name: pg-prod
