---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: serenemind-ingress-prod
  namespace: serenemind
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`serenemind.prod.raulstechtips.dev`)
      kind: Rule
      middlewares:
        - name: strict-referrer
          namespace: serenemind
        - name: default-headers
          namespace: default
      services:
        - name: webapp
          port: 80
  tls:
    secretName: prod-raulstechtips-tls
