---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: infisical-secret-pg-dev-admin-credentials
  namespace: dev
spec:
  hostAPI: "${ARGOCD_ENV_INFISICAL_PROD_HOST_API}"
  authentication:
    universalAuth:
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: infisical
      secretsScope:
        projectSlug: "${ARGOCD_ENV_INFISICAL_PROJECT_SLUG}"
        envSlug: "dev"
        secretsPath: "/cnpg/dev/users/admin"
        recursive: true
  managedKubeSecretReferences:
    - secretName: pg-dev-admin-credentials-secret
      secretNamespace: dev
      secretType: kubernetes.io/basic-auth
      creationPolicy: Owner
      template:
        includeAllSecrets: false
        data:
          username: "{{ .PG_DEV_ADMIN_USERNAME.Value }}"
          password: "{{ .PG_DEV_ADMIN_PASSWORD.Value }}"
