---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: authentik-env
  namespace: authentik
spec:
  hostAPI: "${ARGOCD_ENV_INFISICAL_PROD_HOST_API}"
  authentication:
    universalAuth:
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: infisical
      secretsScope:
        projectSlug: "${ARGOCD_ENV_INFISICAL_PROJECT_SLUG}"
        envSlug: "${ARGOCD_ENV_INFISICAL_ENV_SLUG}"
        secretsPath: "/authentik/env"
        recursive: true
  managedKubeSecretReferences:
    - secretName: authentik-env
      secretNamespace: authentik
      secretType: Opaque
      creationPolicy: Owner
      template:
        includeAllSecrets: false
        data:
          SECRET_KEY: "{{ .SECRET_KEY.Value }}"
          AUTHENTIK_BOOTSTRAP_EMAIL: "{{ .AUTHENTIK_BOOTSTRAP_EMAIL.Value }}"
          AUTHENTIK_BOOTSTRAP_PASSWORD: "{{ .AUTHENTIK_BOOTSTRAP_PASSWORD.Value }}"
          AUTHENTIK_BOOTSTRAP_TOKEN: "{{ .AUTHENTIK_BOOTSTRAP_TOKEN.Value }}"
          AUTHENTIK_POSTGRESQL__HOST: "{{ .AUTHENTIK_POSTGRESQL__HOST.Value }}"
          AUTHENTIK_POSTGRESQL__SSLROOTCERT: "{{ .SSLROOTCERT.Value }}"
          # AUTHENTIK_POSTGRESQL__READ_REPLICAS__0__HOST: "{{ .AUTHENTIK_POSTGRESQL__HOST.Value }}"
          # AUTHENTIK_POSTGRESQL__READ_REPLICAS__0__NAME: "{{ .AUTHENTIK_POSTGRESQL__NAME.Value }}"
          # AUTHENTIK_POSTGRESQL__READ_REPLICAS__0__PORT: "{{ .AUTHENTIK_POSTGRESQL__PORT.Value }}"
          # AUTHENTIK_POSTGRESQL__READ_REPLICAS__0__SSLMODE: "{{ .AUTHENTIK_POSTGRESQL__SSLMODE.Value }}"
          # AUTHENTIK_POSTGRESQL__READ_REPLICAS__0__SSLROOTCERT: "{{ .SSLROOTCERT.Value }}"
          AUTHENTIK_REDIS__HOST: "{{ .AUTHENTIK_REDIS__HOST.Value }}"
          AUTHENTIK_REDIS__TLS: "{{ .AUTHENTIK_REDIS__TLS.Value }}"
          AUTHENTIK_REDIS__TLS_CA_CERT: "{{ .SSLROOTCERT.Value }}"
          AUTHENTIK_REDIS__TLS_REQS: "{{ .AUTHENTIK_REDIS__TLS_REQS.Value }}"
          AUTHENTIK_STORAGE__MEDIA__BACKEND: "{{ .AUTHENTIK_STORAGE__MEDIA__BACKEND.Value }}"
          AUTHENTIK_STORAGE__MEDIA__S3__REGION: "{{ .AUTHENTIK_STORAGE__MEDIA__S3__REGION.Value }}"
          AUTHENTIK_STORAGE__MEDIA__S3__ENDPOINT: "{{ .AUTHENTIK_STORAGE__MEDIA__S3__ENDPOINT.Value }}"
          AUTHENTIK_STORAGE__MEDIA__S3__ACCESS_KEY: "{{ .AUTHENTIK_STORAGE__MEDIA__S3__ACCESS_KEY.Value }}"
          AUTHENTIK_STORAGE__MEDIA__S3__SECRET_KEY: "{{ .AUTHENTIK_STORAGE__MEDIA__S3__SECRET_KEY.Value }}"
          AUTHENTIK_STORAGE__MEDIA__S3__BUCKET_NAME: "{{ .AUTHENTIK_STORAGE__MEDIA__S3__BUCKET_NAME.Value }}"
          AUTHENTIK_STORAGE__MEDIA__S3__CUSTOM_DOMAIN: "{{ .AUTHENTIK_STORAGE__MEDIA__S3__ENDPOINT.Value }}/{{ .AUTHENTIK_STORAGE__MEDIA__S3__BUCKET_NAME.Value }}"
          DREAMHOST_SMTP_USERNAME: "{{ .DREAMHOST_SMTP_USERNAME.Value }}"
          DREAMHOST_SMTP_PASSWORD: "{{ .DREAMHOST_SMTP_PASSWORD.Value }}"
          DREAMHOST_SMTP_HOST: "{{ .DREAMHOST_SMTP_HOST.Value }}"
