---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: redis-authentik-internal-certificate
  namespace: authentik
spec:
  secretName: redis-authentik-internal-tls
  duration: 8760h # 1 year
  renewBefore: 720h # 30 days
  dnsNames:
    - redis-authentik.prod.raulstechtips.dev
    - redis-authentik-master
    - redis-authentik-master.authentik
    - redis-authentik-master.authentik.svc
    - redis-authentik-master.authentik.svc.cluster.local
  issuerRef:
    name: raulstechtips-internal-ca-issuer
    kind: ClusterIssuer
