apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins-agent: ci-test
spec:
  restartPolicy: Never
  volumes:
    - name: kubeconfig
      secret:
        secretName: jenkins-kube-config
        defaultMode: 0400
  containers:
    - name: helm
      image: ghcr.io/helmfile/helmfile:v1.0.0
      command: ["cat"]
      tty: true
      volumeMounts:
        - name: kubeconfig
          mountPath: /home/jenkins/.kube
          readOnly: true
      env:
        - name: KUBECONFIG
          value: /home/jenkins/.kube/config
    - name: yq
      image: mikefarah/yq:4.21.1
      command: ["cat"]
      tty: true
    - name: validator
      image: ghcr.io/yannh/kubeconform:v0.6.7
      command: ["/kubeconform", "-h"]
      tty: true
