---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: serenemind

resources:
  - manifests/ingress/prod.yaml
  - manifests/secrets/github-registry-secret.yaml
  - manifests/secrets/app-secret.yaml
  - manifests/secrets/s3-secret.yaml
  - manifests/app.yaml
