---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-redis-infisical
  namespace: infisical
provisioner: driver.longhorn.io
parameters:
  numberOfReplicas: "3"
  staleReplicaTimeout: "1440" # 24 hours in minutes
  volumeExpansion: "true"
